### ISSUE TITLE
[功能请求] | [Feature Request] V3 API适配

### ISSUE THREAD

**Issue by cutestAlpaca** [chenmingyong0423/go-coze#1]
### 新API适配

>  希望大佬适配coze最新V3接口，新API已经使用OAuth授权方式。

---

>  文档在 https://www.coze.cn/docs/developer_guides/coze_api_overview

**Comment by chenmingyong0423** [comment]
好的，我看看。

**Comment by chenmingyong0423** [comment]
升级 Chat V2 到 V3 功能，添加查看消息详情以及消息列表功能，这几天会补充消息、文件之类的接口方法。
